version: '3.7'

networks:
  go_zero_beyond:
    driver: bridge

services:
  redis:
    container_name: beyond_redis
    image: bitnami/redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/bitnami/redis/data
      - redis-conf:/opt/bitnami/redis/mounted-etc
#      - /etc/localtime:/etc/localtime:ro
    networks:
      - go_zero_beyond

  mysql:
    container_name: beyond_mysql
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai
    volumes:
      - mysql-conf:/etc/mysql/conf.d
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - go_zero_beyond
  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: beyond_zookeeper
    restart: always
    ports:
      - "2181:2181"
#    volumes:
#      - "zookeeper_data:/bitnami"
#      - /etc/localtime:/etc/localtime:ro
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - go_zero_beyond

  kafka:
    image: 'bitnami/kafka:3.4'
    container_name: beyond_kafka
    restart: always
    hostname: kafka
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://119.45.147.122:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - ALLOW_PLAINTEXT_LISTENER=yes
      - "KAFKA_HEAP_OPTS=-Xmx512m -Xms512m"
#    volumes:
#      - kafka-conf:/bitnami/kafka/config
#      - kafka-data:/bitnami/kafka/data
#      - /etc/localtime:/etc/localtime:ro
    networks:
      - go_zero_beyond

  kafka-ui:
    container_name: beyond_kafka-ui
    image: provectuslabs/kafka-ui:latest
    restart: always
    ports:
      - 8090:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: kafka-dev
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
#    volumes:
#      - kafkaui-app:/etc/kafkaui
#      - /etc/localtime:/etc/localtime:ro
    networks:
      - go_zero_beyond

  consul:
    container_name: beyond_consul
    image: bitnami/consul:latest
    restart: always
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
    networks:
      - go_zero_beyond

volumes:
  redis-data:
  redis-conf:
  mysql-conf:
  mysql-data:


